# Generated by Django 5.1.1 on 2024-11-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocuCareDHManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
