# Generated by Django 5.1.2 on 2024-11-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocuCareDHManagement', '0002_medicaltest'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
